### PR TITLE
Fixed Invalid Webhook Issue

### PR DESCRIPTION
**Pull request by nickswink**
There is an extra space now in the string that is checked in the response from Discord. They have updated the discord API to contain "type:1" instead of "type: 1".

### CODE REVIEW

**Comment by Yanoboku** [comment]
Still have this issue, tried adding space before too, nothing changed

**Comment by googledino** [comment]
Also still having the issue

**Comment by ilcanegamer** [comment]
revert it back  to type:1 and it works, at least for me

**Comment by Flinggoo** [comment]
image
help

**Pull request closed without merging**
